### ISSUE TITLE
`ReferenceError: process is not defined`

### ISSUE THREAD

**Issue by charlesfries** [Iterable/iterable-web-sdk#185]
Windows 10
Google Chrome 108.0.5359.126

```js
import { initialize } from '@iterable/web-sdk/dist/authorization';
initialize('xxx');
```

`constants.js:4 Uncaught (in promise) ReferenceError: process is not defined`

Appears to be due to the use of the `process` obj in `src/constants.ts`. Is this library meant for Node or the browser?

**Comment by monfrid** [comment]
importing from "@iterable/web-sdk" works

**Comment by charlesfries** [comment]
@monfrid thank you. Are you able to share any working code? I am trying to call `initialize` without JWT, but it appears to return undefined:

```js
import { initialize } from '@iterable/web-sdk';

const result = initialize('xxx');
console.log(result); // undefined

result.setEmail(...);
result.logout();
```

**Comment by monfrid** [comment]
ah sorry, I do not have a working code w/o JWT, I am using it with JWT

**Comment by mprew97** [comment]
Closing since the root issue has been resolved. Feel free to open a discussion/issue if you are unable to initialize without a JWT.

**Comment by sc-yan** [comment]
@charlesfries hi just wonder how you fixed the issue? did you do this? 
https://github.com/vitejs/vite/issues/1973

**Comment by martinmckenna** [comment]
@sc-yan @charlesfries this one is actually an oversight. you'll see that the `.env` variables are actually being added in the webpack config files: https://github.com/Iterable/iterable-web-sdk/blob/main/webpack.config.js

The issue here is all the files built in the `/dist` directory aren't touched by Webpack - only Babel. Webpack is purely responsible for bundling all the files in the `/dist` directory together and adding the `process.env` variables at that point.

This means the fix for this is most likely going to have to involve removing all the `.env` logic from the Webpack config files and instead use something like the [babel-plugin-inline-dotenv](https://github.com/brysgo/babel-plugin-inline-dotenv) to add the environment variables at the time Babel transpiles the code and creates the `/dist` files, so both the `/dist` files and the root `index.js` file has access to those variables.

It's worth noting, importing from `@iterable-web-sdk/dist/whatever` is only going to be an issue for non webpack-based project like Vite.

**Comment by sc-yan** [comment]
@martinmckenna  thanks so much for the explanation! yeah I am using vite to build our app, not webpack. 
so I guess there is no way to fix this when using vite but have to call iterable APIs in back-end instead of in browser. 🤔 
can I open an issue to request a support for vite building?

**Comment by martinmckenna** [comment]
@sc-yan importing from the root should still work for you in the browser `import { blah } from '@iterable/web-sdk'` vs `import { blah } from '@iterable/web-sdk/dist/whatever'`

**Comment by sc-yan** [comment]
thank you for the reply! it is working! also I found it is written in [docs](https://github.com/Iterable/iterable-web-sdk#a-note-about-imports) actually. should have read it carefully. thank you!
